version: '3'

volumes:
  bundle:
  javascript:
  node_modules:
  db:
  redis:

services:
  app:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - .:/app/
      - ./docker/dev/entrypoint.sh:/app/docker/dev/entrypoint.sh
      - bundle:/usr/local/bundle
      - javascript:/app/vendor/javascript
      - node_modules:/app/node_modules
    entrypoint: /app/docker/dev/entrypoint.sh
    ports:
      - 3000:3000
    env_file: 
      - .env
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  redis:
    image: redis:7.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - redis:/data
